DATA:
  NAME: "R2R"
  DATA_DIR: "tasks/R2R-judy/data"
  TRAIN_VOCAB: "tasks/R2R-judy/data/train_vocab.txt"
  TRAINVAL_VOCAB: "tasks/R2R-judy/data/trainval_vocab.txt"
  IMG_FEAT_DIR: "img_features/ResNet-152-imagenet.tsv"
  MAX_ENC_LEN: 80

OUTPUT:
  RESUME: ""
  CKPT_DIR: "tasks/R2R-judy/snapshots/checkpoints/follower/normal"
  LOG_DIR: "tasks/R2R-judy/snapshots/logs"
  RESULT_DIR: "tasks/R2R-judy/snapshots/trajs"
  TSBOARD_DIR: "tasks/R2R-judy/snapshots/tensorboard/follower"

TRAIN: 
  DEVICE: 0
  OPTIM: "adam"
  LR: 0.0001
  BATCH_SIZE: 64
  START_EPOCH: 1
  MAX_EPOCH: 200
  ITER_PER_EPOCH: 200
  EVAL_INTERVAL: 2
  PATIENCE: 3
  LR_MIN: 1e-6
  DATA_ARGUMENT: False

AGENT:
  TEACHER_FORCE: False
  MAX_EPISODE_LEN: 10
  FEEDBACK: "sample"

MODEL:
  NAME: "FOLLOWER"

  FOLLOWER:
    GLOVE_PATH: ""
    WORD_EMB_SIZE: 300
    HIDDEN_SIZE: 256
    DROP_RATE: 0.5
    ENC_BIDIRECTION: True
    ENC_LAYERS: 2
