REGION_LABELS = {
    'a' : 'bathroom (should have a toilet and a sink)',
    'b' : 'bedroom',
    'c' : 'closet',
    'd' : 'dining room (includes “breakfast rooms” other rooms people mainly eat in)',
    'e' : 'entryway/foyer/lobby (should be the front door, not any door)',
    'f' : 'familyroom (should be a room that a family hangs out in, not any area with couches)',
    'g' : 'garage',
    'h' : 'hallway',
    'i' : 'library (should be room like a library at a university, not an individual study)',
    'j' : 'laundryroom/mudroom (place where people do laundry, etc.)',
    'k' : 'kitchen',
    'l' : 'living room (should be the main “showcase” living room in a house, not any area with couches)',
    'm' : 'meetingroom/conferenceroom',
    'n' : 'lounge (any area where people relax in comfy chairs/couches that is not the family room or living room',
    'o' : 'office (usually for an individual, or a small set of people)',
    'p' : 'porch/terrace/deck/driveway (must be outdoors on ground level)',
    'r' : 'rec/game (should have recreational objects, like pool table, etc.)',
    's' : 'stairs',
    't' : 'toilet (should be a small room with ONLY a toilet)',
    'u' : 'utilityroom/toolroom ',
    'v' : 'tv (must have theater-style seating)',
    'w' : 'workout/gym/exercise',
    'x' : 'outdoor areas containing grass, plants, bushes, trees, etc.',
    'y' : 'balcony (must be outside and must not be on ground floor)',
    'z' : 'other room (it is clearly a room, but the function is not clear)',
    'B' : 'bar',
    'C' : 'classroom',
    'D' : 'dining booth',
    'S' : 'spa/sauna',
    'Z' : 'junk (reflections of mirrors, random points floating in space, etc.)',
    '-' : 'no label'
}